### ISSUE TITLE
Ideas for examples

### ISSUE THREAD

**Issue by lucacasonato** [denoland/denobyexample#5]
This is a list of examples we'd like to add. Before contributing an example, please read the instructions in the README.md file. Please also comment on this issue with the example you'd like to write up so we don't duplicate effort.

Ideas (in no particular order):
- [x] Running a subprocess to completion #61 
- [x] Spawning a subprocess and interacting with it #65 
- [x] Handling OS signals
- [x] Getting the Deno version (@ry, https://github.com/denoland/denobyexample/pull/14)
- [x] Programatically request and query permissions
- [x] Get current process information (pid, ppid, etc) (@ry, https://github.com/denoland/denobyexample/pull/14)
- [x] Get list of current environment variables
- [x] Logging with colors
- [x] Connecting to a TCP server 
- [x] Starting a TCP listener
- [x] Streaming HTTP server responses
- [x] Serving local files using HTTP server #59 
- [x] Creating temporary files and directories
- [x] Writing tests (including substeps, resource leakage, and std asserts) #79 
- [x] Getting a directory listing (including reccursive)
- [x] Moving / renaming files
- [x] Removing files / directories #67
- [x] Checking for file existence (explain that you should just do the operation and catch errors)
- [x] Handling WebSocket connections in a HTTP server #70 
- [x] Creating outbound WebSocket connections #69 
- [x] Watching the file system for changes (including how to debounce)
- [x] Running DNS queries (@satyarohith)
- [x] Sending UDP packets (@satyarohith) #80 
- [x] Listening for UDP packets (@satyarohith) #80 
- [x] Starting TLS connections (including custom CA certs, and other options) (@satyarohith)
- [x] Start a TLS listener (@satyarohith)
- [x] Piping streams
- [x] How to do benchmarking
- [x] Calculating cryptographic digests (hashing) (@littledivy)
- [x] Manipulating byte buffers (read / write u8/u16/i32/i64 etc, concatenate buffers using std/bytes) (@littledivy)
- [x] Generating UUIDs
- [x] Manipulating fs paths (join, normalize, etc) #62 
- [x] Manipulating and parsing URLs #72 
- [x] Matching URLs with `URLPattern`
- [x] Parsing flags
- [x] Hex and base64 encoding
- [x] Parsing / outputting TOML
- [x] Parsing / outputting YAML
- [x] Parsing / outputting CSV
- [x] Parsing / outputting JSON (@lucacasonato)
- [x] Using JSON modules with `assert { type: "json" }`
- [x] Creating & Resolving Symlinks #68
- [x] Using Web Workers
- [x] Deno.File to Web Streams #71

**Comment by zachauten** [comment]
I noticed denoland/manual#161 recently, seems like something that could go here. I could add it if there's interest.

**Comment by LeoDog896** [comment]
Working on the shebang example right now.

**Comment by lino-levan** [comment]
I feel like this checklist should be updated to fit the current status of by example:
- Parsing / outputting YAML #33 
- Parsing / outputting TOML #32 
- benchmarking #34 
- os signals #39 
- watching the filesystem #37

**Comment by WingZer0o** [comment]
I like to work on the TCP listener.

**Comment by lino-levan** [comment]
Another round of updates that should probably be checked on the list:
- Running DNS queries #48
- Starting a TCP listener #47
- Connecting to a TCP server #41
- Programatically request and query permissions #43

**Comment by lino-levan** [comment]
Another another round of updates:

-  Running a subprocess to completion (https://github.com/denoland/denobyexample/pull/61)
-  Spawning a subprocess and interacting with it (https://github.com/denoland/denobyexample/pull/65)
- Serving local files using HTTP server (https://github.com/denoland/denobyexample/pull/59)
- Removing files / directories (solved indirectly in other PRs, do we want a dedicated example for something so simple?)
- Manipulating fs paths (join, normalize, etc) (https://github.com/denoland/denobyexample/pull/62)

This should leave us with 10 more examples in this main batch. I'll be writing drafts for each of these in the upcoming week (though if anyone else is interested in doing them, please feel free!).

**Comment by kt3k** [comment]
> do we want a dedicated example for something so simple?

I think a dedicated example would be useful for some users

**Comment by lino-levan** [comment]
Yet another round of updates:
- Writing tests (including substeps, resource leakage, and std asserts) #79 
- Removing files / directories #67 
- Handling WebSocket connections in a HTTP server #70 
- Creating outbound WebSocket connections #69 
- Sending UDP packets #80 
- Listening for UDP packets #80
- Manipulating and parsing URLs #72 
- Creating & Resolving Symlinks #68 
- Deno.File to Web Streams #71 

This should leave
- Starting TLS connections (including custom CA certs, and other options)
- Start a TLS listener
  - No idea why this is checked, we don't have an example for this
- Piping streams
  -  Not on the list at the moment but suggested by @kt3k in https://github.com/denoland/denobyexample/pull/71#issuecomment-1507872879

**Comment by lino-levan** [comment]
This issue should be closed. All of the remaining examples have been added. New examples should get dedicated issues (like ULID).

**Comment by kt3k** [comment]
@lino-levan Thank you for your efforts on this! 👏 👏

**Comment by lino-levan** [comment]
@kt3k could you unpin this issue?

**Comment by kt3k** [comment]
Thanks for pointing. Unpinned 👍
